Repository silverstripe/silverstripe-webauthn-authenticator, pull requests merged in 2019-07, with the labels that each got.

#42 FIX Look for HTTPS in frontend availability check before WebAuthn API presence
  client/dist/js/bundle.js
  client/src/state/tests/webauthnAvailableReducer-test.js
  client/src/state/webauthnAvailableReducer.js
Labels: affects/v4, change/patch

#44 DOCS Update docs to provide a little more information about what WebAuthn is
  README.md
  docs/en/readme.md
Labels: affects/v4, type/docs

#45 Adjust user help link text default translations
  client/dist/js/bundle.js
  client/lang/src/en.json
  client/src/components/WebAuthn/Register.js
  docs/en/readme.md
  src/RegisterHandler.php
Labels: affects/v4, change/major
