Repository silverstripe/silverstripe-webauthn-authenticator, pull requests merged in 2019-08, with the labels that each got.

#52 FIX Convert actions toolbar to be consistent with mfa/totp
  client/dist/js/bundle.js
  client/src/components/WebAuthn/Register.js
  client/src/components/WebAuthn/Verify.js
  package.json
Labels: affects/v4, change/patch

#54 NEW Add links to userhelp documentation
  src/RegisterHandler.php
Labels: affects/v4, change/minor

#55 Adjust styling to support Dark Mode
  client/dist/styles/bundle.css
  client/src/components/WebAuthn/Register.scss
  client/src/components/WebAuthn/Verify.scss
  client/src/styles/variables.scss
Labels: affects/v4, change/minor

#53 API Implemented the non-deprecated interface for credential repository
  src/CredentialRepository.php
  src/CredentialRepositoryProviderTrait.php
  src/RegisterHandler.php
  src/VerifyHandler.php
  tests/CredentialRepositoryTest.php
  tests/RegisterHandlerTest.php
  tests/VerifyHandlerTest.php
Labels: affects/v4, change/major

#56 FIX Images now resolve correctly when project is installed in a subfolder
  src/Method.php
  src/RegisterHandler.php
Labels: affects/v3, change/patch
